name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    docker:
      - image: elixir:1.11.1
        environment:
          MIX_ENV: test
      - image: postgres:11.1-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: postgres_test
          POSTGRES_DB: scm_test
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.10.3'
          otp-version: '22.3'
      - run: mix deps.get
      - run: mix deps.compile
      - run: cd assets && yarn install --frozen-lockfile
      - run: MIX_ENV=test mix test.init
      - run: MIX_ENV=test mix ecto.migrate
      - run: MIX_ENV=test mix test
          